cd('~/')
#shell('python fftp.py')
shell('del zwc*')
shell('ftp -i -s:u.ftp')
dd=readLines('~/xfer.yaml')
ee=fi('Node id',dd)
ff=fi('name',ee)
mm=strsplit(ff,'NodeId=|Name=| ')
nn=sapply(1:len(mm), function(x){mm[[x]]}[2])
ccc=gregexpr('[0-9]',nn)
zz=sapply(2:len(ccc), function(x){ccc[[x]]}[1])
nodes=as.integer(substr(nn[2:len(nn)],5,6))
print(nodes)

